In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/AAPL.csv")
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600
...,...,...,...,...,...,...,...
10404,2022-03-18,160.509995,164.479996,159.759995,163.979996,163.979996,123351200
10405,2022-03-21,163.509995,166.350006,163.009995,165.380005,165.380005,95811400
10406,2022-03-22,165.509995,169.419998,164.910004,168.820007,168.820007,81532000
10407,2022-03-23,167.990005,172.639999,167.649994,170.210007,170.210007,98062700
10408,2022-03-24,171.059998,174.139999,170.210007,174.070007,174.070007,90018700

In [ ]:
print(df.head())

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.100323  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.095089  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.088110  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.090291   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092908   73449600

In [ ]:
print(df.info)

<bound method DataFrame.info of              Date        Open        High         Low       Close   Adj Close  \
0      1980-12-12    0.128348    0.128906    0.128348    0.128348    0.100323
1      1980-12-15    0.122210    0.122210    0.121652    0.121652    0.095089
2      1980-12-16    0.113281    0.113281    0.112723    0.112723    0.088110
3      1980-12-17    0.115513    0.116071    0.115513    0.115513    0.090291
4      1980-12-18    0.118862    0.119420    0.118862    0.118862    0.092908
...           ...         ...         ...         ...         ...         ...
10404  2022-03-18  160.509995  164.479996  159.759995  163.979996  163.979996
10405  2022-03-21  163.509995  166.350006  163.009995  165.380005  165.380005
10406  2022-03-22  165.509995  169.419998  164.910004  168.820007  168.820007
10407  2022-03-23  167.990005  172.639999  167.649994  170.210007  170.210007
10408  2022-03-24  171.059998  174.139999  170.210007  174.070007  174.070007

          Volume
0      469033600
1      175884800
2      105728000
3       86441600
4       73449600
...          ...
10404  123351200
10405   95811400
10406   81532000
10407   98062700
10408   90018700

[10409 rows x 7 columns]>

In [ ]:
df = df.dropna()
df = df.drop_duplicates()
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600
...,...,...,...,...,...,...,...
10404,2022-03-18,160.509995,164.479996,159.759995,163.979996,163.979996,123351200
10405,2022-03-21,163.509995,166.350006,163.009995,165.380005,165.380005,95811400
10406,2022-03-22,165.509995,169.419998,164.910004,168.820007,168.820007,81532000
10407,2022-03-23,167.990005,172.639999,167.649994,170.210007,170.210007,98062700
10408,2022-03-24,171.059998,174.139999,170.210007,174.070007,174.070007,90018700

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_excel("/content/AAPL.excel.xlsx")

print(df.head())

        Date        Open        High         Low       Close   Adj Close  \
0 2014-09-29  100.589996  100.690002   98.040001   99.620003   93.514290
1 2014-10-06   99.949997  102.379997   98.309998  100.730003   94.556244
2 2014-10-13  101.330002  101.779999   95.180000   97.669998   91.683792
3 2014-10-20   98.320000  105.489998   98.220001  105.220001   98.771042
4 2014-10-27  104.849998  108.040001  104.699997  108.000000  101.380676

      Volume
0  142718700
1  280258200
2  358539800
3  358532900
4  220230600

In [ ]:
print(df.tail())

          Date        Open        High         Low       Close   Adj Close  \
179 2018-03-05  175.210007  180.000000  174.270004  179.979996  179.979996
180 2018-03-12  180.289993  183.500000  177.619995  178.020004  178.020004
181 2018-03-19  177.320007  177.470001  164.940002  164.940002  164.940002
182 2018-03-26  168.070007  175.149994  165.190002  167.779999  167.779999
183 2018-03-29  167.804993  171.750000  166.899994  167.779999  167.779999

        Volume
179  139852700
180  155417500
181  172670700
182  157898400
183   38398505

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       184 non-null    datetime64[ns]
 1   Open       184 non-null    float64
 2   High       184 non-null    float64
 3   Low        184 non-null    float64
 4   Close      184 non-null    float64
 5   Adj Close  184 non-null    float64
 6   Volume     184 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 10.2 KB

In [ ]:
print(df.columns)

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [ ]:
print(df.dtypes)

Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [ ]:
print(df.describe())

                                Date        Open        High         Low  \
count                            184  184.000000  184.000000  184.000000
mean   2016-06-30 11:28:41.739130368  127.040245  129.918098  124.340381
min              2014-09-29 00:00:00   92.389999   93.769997   89.470001
25%              2015-08-15 06:00:00  108.882499  112.362499  106.152502
50%              2016-06-30 12:00:00  118.895000  120.865002  116.870003
75%              2017-05-16 18:00:00  144.935005  147.695000  143.227493
max              2018-03-29 00:00:00  180.289993  183.500000  177.619995
std                              NaN   24.314449   24.577906   24.176736

            Close   Adj Close        Volume
count  184.000000  184.000000  1.840000e+02
mean   127.352663  123.838032  1.910168e+08
min     90.519997   87.796822  3.839850e+07
25%    109.204998  105.301765  1.273706e+08
50%    119.190002  114.999730  1.744112e+08
75%    144.704994  143.039467  2.207755e+08
max    179.979996  179.979996  5.003630e+08
std     24.356534   25.655569  8.160281e+07

In [ ]:
df = df.dropna()

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])

In [ ]:
df = df.sort_values("Date")

In [ ]:
print(df.head())

        Date        Open        High         Low       Close   Adj Close  \
0 2014-09-29  100.589996  100.690002   98.040001   99.620003   93.514290
1 2014-10-06   99.949997  102.379997   98.309998  100.730003   94.556244
2 2014-10-13  101.330002  101.779999   95.180000   97.669998   91.683792
3 2014-10-20   98.320000  105.489998   98.220001  105.220001   98.771042
4 2014-10-27  104.849998  108.040001  104.699997  108.000000  101.380676

      Volume
0  142718700
1  280258200
2  358539800
3  358532900
4  220230600

In [ ]:
print(df.dtypes)

Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object